// Express app setup
import express from 'express';
import fileIntakeRoutes from './file-intake/routes/fileIntake';
import x12ParserRoutes from './x12-parser/routes/x12Parser';
import claimRoutes from './claim-management/routes/claims';
import businessValidationRoutes from './business-validation/routes/businessValidation';
import masterDataRoutes from './master-data/routes/masterData';
import workflowRoutes from './workflow/routes/workflow';
import submissionRoutes from './submission/routes/submission';
import reportingRoutes from './reporting/routes/reporting';
import denialsMLRoutes from './denials-ml/routes/denialsML';
const app = express();
app.use(express.json());
app.use('/file-intake', fileIntakeRoutes);
app.use('/x12-parser', x12ParserRoutes);
app.use('/claims', claimRoutes);
app.use('/business-validation', businessValidationRoutes);
app.use('/master-data', masterDataRoutes);
app.use('/workflow', workflowRoutes);
app.use('/submission', submissionRoutes);
app.use('/reporting', reportingRoutes);
app.use('/denials-ml', denialsMLRoutes);
export default app;